### ISSUE TITLE
Fix all business logic & little pain points 

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#70]
There is so much business logic that needs fixing and is so important for users so the app flows a little nicer and fix pain points such as documentation, API for developers and in-app consistency and SEO for better user.

Fix / add these tickets:
- [x] #68 
- [x] #26 
- [x] #60 
- [x] #65 

## Legal documents 
- [ ] Write terms of service agreement 
- [x] Update privacy policy 
- [x] Add in certain parts `beta` and info about importing

## Documentation 
- [ ] flesh out the doc's 
- [ ] add any new information from the latest upgrades 

## UI / UX
- [x] Footer this must contain:
- Privacy policy
- Terms of service
- about

## Overall:
- [x] Reduce calls to database to as little as possible so it reduces data used for development and unessary querying to db 
- [x] fix data querying that isn't public 
- [x] better auth 
- [x] move everthing to API's or as much as possible
- [x] Dialogs to be better styled and more responsive

## Recipe Form: 
- [ ] Ingredient bug for cup, tsp, tbsp (this adds a new item if one of the items is chosen)
- [x] ingredient unit to be searchable / filter on search
- [x] for headings add margin-top 
- [x] Dietry requirements: multi select, searchable
- [x] Meal time to multiple select 
- [x] Better DND
- [x] Ingredient title first letter will go to uppercase onSubmit or after typing
- [x] Image upload: alt to text area, user uploads 
- [x] Publish dialog: loading spinner, close on save with toast
- [x] add auth for editing of recipes
### Imports:
- [ ] Make it so users can import from text e.g paste a recipe in from instagram or something like: https://www.instagram.com/p/CuNs5e6pRXw/ in the desciption there is a recipe so maybe handle imports like that, might integrate NLP 
- [ ] letting users know about keeping them private and what not / changing them 

## Main page: 
- [ ] make it more pretty
- [x] Fix coursel 

## Recipe page:
- [ ] Share button (could be a dialog or proper share)
- [ ] better ingreients chip searching 
- [x] Custom printing view
- [x] Ui for ticking off ingredinets and steps 
- [x] Better responsive design
- [x] setting a rating on a recipe 
- [x] Move notes to be under the line 
- [x] For imports of recipe to set a rating on it during creation

## Sign in / Sign up / Users
- [x] Build a sign-in page
- [x] Build the customization page for the user if they are signing up 
- [x] Rework to use the passwordless sign, e.g. email, Google, Facebook, GitHub
(Notes: Don't add Facebook and Google if they aren't working because they need approval first before they can be used in production) 
- [x] Get emails to be sent out 

### User profile
- [ ] Add a user profile page
- [ ] edit settings

## SEO, PWA
- [ ] Get my app with be full PWA  *(Note: will improve my SEO)*
- [ ] (Maybe) Switch to using `Preact` 
- [ ] Sitemap generation, both pages that will always be there and dynamic routes as well 
- [x] For `/recipes/[id]` and main pages make it revalidate every day with data and statically build

## API's
- [x] Rework my app a little to use `tRPC` and `React Query`
- [x] Update my APIs to use some Auth *(Note: can keep this in the database and be useful if someone wanted to access data)*
### Recipes
- [x] Add an API route using `tRPC` for importing recipes from a URL 

## Update types
- [x] Drizzle schemes add the `.$type` for JSON columns 
- [x] Make sure all Enums and zod schemas are correct and make sense 
- [x] Import statements for typescript

**Comment by Jacobsamo** [comment]
## API authentication 
Dealing with authenticating the API and also keeping it safe from attackers is import.

This is why an approach of using `JWT` or hashing response body is import

For routes that is dealing with user data will be sent back using `JWT` and i think this is the best way to deal with all other authenticating. 


TODO:
- [ ] `/users/*` need to be sent back using `JWT` 
- [ ] API `authorization` header to be using `JWT` to send to the server and then decrypt 
- [ ] For `/recipes/create` and `/recipes/[id]/edit` authenticate who is actually updating to make sure it is the person is lastupdated or person who owns the recipe
